version: "3.7"

services:

  traefik:
    image: "traefik:v2.1.1"
    container_name: "traefik"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    dns:
      - host.docker.internal
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik.toml:/etc/traefik/traefik.toml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`dashboard.docker.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
      
networks:
  web:
   name: traefik_web